app:
  clients:
    llm:
      token: "llm_api_token"
      url: "http://localhost:9999"
      timeout: 1m
  processor:
    workers_count: 10
    max_retries: 2
    retry_delay: 10s
  postgres:
    host: postgres
    port: 5432
    user: user
    password: password
    dbname: db
    sslmode: disable
  logger:
    loglvl: debug
    mode: development
    encoding: json

kafka:
  group_id: "vixar_processor"
  brokers:
    - kafka:9093
  topics:
    scraper_data: "scraper_data"
