app:
  service:
    session_secret: "dev_session_secret"
  http:
    port: "8000"
  cors:
    allow_origins: ["http://localhost:3000"]
    allow_credentials: true
    max_age: 24h
  logger:
    loglvl: debug
    mode: development
    encoding: json
  scheduler:
    refresh_search_table_pattern: "*/1 * * * *"  # for testing, every minute
  vk:
    http:
      timeout: 5s
    auth:
      url: "https://id.vk.ru"
      client_id: "54376847"
    secret: "dev_secret"

postgres:
  host: postgres
  port: 5432
  user: user
  password: password
  dbname: db
  sslmode: disable

redis:
  addr: localhost:6379
  password: ""
  db: 0