app:
  cookie:
    session:
      name: "session_id"
      expiration: 4320h  # 180 days
  service:
    user:
      session_secret: "dev_session_secret"
  http:
    port: "8000"
  cors:
    allow_origins: ["http://localhost:3000", "http://localhost:80", "http://localhost"]
    allow_credentials: true
    max_age: 24h
  logger:
    loglvl: debug
    mode: development
    encoding: json
  scheduler:
    refresh_search_table_pattern: "18 * * * *" # configure cron pattern for testing
  vk:
    http:
      timeout: 5s
    auth:
      url: "https://id.vk.ru"
      client_id: "54390662"
    secret: "dev_secret"

postgres:
  host: postgres
  port: 5432
  user: user
  password: password
  dbname: db
  sslmode: disable

redis:
  addr: "redis:6379"
  password: "dev_redis_password"
  db: 0

kafka:
  max_retry: 5
  brokers:
    - kafka:9093
  topics:
    notifications: "notifications"
